version: '3'

services:
  backend: 
    image: 'void-backend'
    container_name: 'void-backend'
    build: 
      context: .
      dockerfile: '.docker/Dockerfile'
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - ingress
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init-scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      ingress: 
        ipv4_address: 10.5.0.5
# # Names our volume
volumes:
  db:
    driver: local

networks:
  ingress:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16